apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  database_url: mysql-service
  my.cnf: | # This is the configuration file for MySQL
    [mysqld]
    transaction-isolation = READ-COMMITTED