apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"
  # volumeName: static-files-pv